<?xml version="1.0" encoding="utf-8"?><Database Name="Turistic" Class="DataClasses2DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=ISE4-06;Initial Catalog=Turistic;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="TuristicConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.sitios" Member="sitios">
    <Type Name="sitios">
      <Column Name="idsitio" Type="System.Int64" DbType="BigInt NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="latitud" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="longitud" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="descripcion" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="lugarcercano" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>